<div id="main-artikel">
    <article>
        <p><strong>LIMA</strong> tahun lalu, Muhammad Arsyad memutuskan meninggalkan kampung halamannya di Makassar setelah ia terjerat Undang-Undang Nomor 11 Tahun 2008 tentang Informasi dan Transaksi Elektronik (UU ITE). “Saya sempat depresi selama dipenjara dan keluarga juga tertekan,” kata Arsyad menceritakan ulang kisahnya itu pada Kamis, 24 Oktober 2019.</p>
        <p>Aktivis antikorupsi di Makassar ini menjadi tersangka dalam kasus pencemaran nama baik atas laporan yang dimasukkan Wahab Tahir pada 9 Juli 2013. Pengurus Golkar Makassar itu menuding Arsyad telah menghina politikus senior Golkar, Nurdin Halid. Pangkal laporan ini adalah status Arsyad di BlackBerry yang berbunyi, “No fear Ancaman Nurdin Halid Koruptor!!! Jangan Pilih Adik Koruptor.”</p>
        <iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110067953001' allowfullscreen frameborder=0></iframe>
        <figcaption> Pengakuan para korban UU ITE - TEMPO </figcaption>
        <p>Persis dua bulan setelah laporan itu, Kepolisian Daerah Sulawesi Selatan menetapkan Arsyad sebagai tersangka. Polisi pun menahan Arsyad. Sebab, kala itu UU ITE belum direvisi. Berdasarkan beleid lama aturan ini, ancaman hukuman untuk pelaku yang terjerat pasal penghinaan nama baik adalah enam tahun.</p>
        <p>Perkara Arsyad melaju mulus sampai ke pengadilan. Dalam pembacaan tuntutan, Kejaksaan Negeri Makassar meminta majelis hakim menghukum Arsyad tujuh bulan penjara karena terbukti mencemarkan nama baik Nurdin Halid.</p>
        <img src="foto/1.jpg" alt="grafis tempo">
        <figcaption> Grafis Perjalanan Revisi UU ITE - TEMPO </figcaption>
        <p>Beruntung, Majelis Hakim Pengadilan Negeri Makassar membebaskan Arsyad pada 28 Mei 2014. “Tidak terbukti secara sah melakukan tindak pidana sesuai dengan tuntutan Jaksa maka harus dibebaskan dari segala tuntutan jaksa. Dan majelis Hakim memerintahkan supaya Arsyad dibebaskan dan segera dikeluarkan dari tahanan,” ujar majelis seperti dikutip Safenetvoice.org.</p>
        <p>Arsyad bebas. Namun, kata dia, kehidupannya susah. “Menyandang status pernah masuk penjara saya kesulitan mendapat kerja,” kata dia. Keluarga pun memutuskan menjual rumah yang ada di Makassar dan pindah ke pinggiran Sulawesi Selatan. Sementara itu, Arsyad merantau ke Ibu Kota.</p>
        <p>Sempat menjadi staf ahli anggota DPR, Arsyad kemudian mengambil lisensi sebagai pengacara. Sekarang, Arsyad merupakan Koordinator Paguyuban Korban UU ITE (Paku ITE). Ia fokus mengadvokasi orang-orang yang terjerat Undang-undang Informasi dan Transaksi Elektronik.</p>
<div class="flourish-embed" data-src="visualisation/999983"></div><script src="https://public.flourish.studio/resources/embed.js"></script>
        <p>Southeast Asia Freedom of Expression Network (SAFENet) Indonesia mencatat ada 381 kasus UU ITE sepanjang 2011 sampai 2019 yang menjerat baik perorangan maupun institusi. “Angka ini bisa lebih besar, karena kami hanya mencatat yang terpantau di media massa dan aduan,” kata Koordinator SAFENet Indonesia, Damar Juniarto kepada Tempo, Jumat, 15 November 2019. SafeNet adalah organisasi nirlaba yang fokus pada perlindungan kebebasan berekspresi di dunia maya.</p>
        <p>Menurut Damar, jika merujuk pada situs registrasi Mahkamah Agung, ada 508 perkara di pengadilan yang menggunakan UU ITE sepanjang 2011-2018. Ia mengatakan kasus paling besar terjadi pada 2018 yaitu 292 perkara. Angka ini meningkat dibanding tahun 2017, sebanyak 140 kasus. Sengketa sepanjang 2018 ini bahkan melebihi dari total 2011-2017 yaitu 216 kasus.</p>
        <img src="foto/2.jpg" alt="grafis tempo">
        <figcaption> Grafis Jumlah Kasus UU ITE - TEMPO </figcaption>
        <p>Damar mengatakan kasus terbanyak adalah pidana yang berhubungan dengan penghinaan dan pencemaran nama baik atau defamasi, Pasal 27 ayat 3 UU ITE. Di posisi kedua adalah kasus ujaran kebencian pasal 28 ayat 2 UU ITE.</p>
        <p>Menurut Damar, kedua sejoli ini memiliki tafsir yang sangat lentur sehingga banyak orang bisa dengan mudah terjerat. “Persoalan lain, ada aturan-aturan yang sering kali tak dipahami oleh penyidik di kepolisian,” kata Damar. “Misalnya dalam penggunaan pasal pencemaran nama baik.”</p>
        <p>Persoalan lain, kata Damar, adalah penyidik yang sering mengabaikan definisi dari pencemaran nama baik atau defarmasi. Ia menjelaskan, Pasal 27 dalam beleid ini  Pasal 27 ini menginduk pada Pasal 310 ayat (1) KUHP.  Dalam KUHP,  defarmasi adalah perbuatan menyerang kehormatan atau nama baik seseorang dengan menuduhkan sesuatu hal yang maksudnya terang supaya hal itu diketahui umum.</p>
        <p>Nah, Damar meneruskan, idealnya penyidik kepolisian mendatangkan saksi ahli yang tepat untuk membedah terminologi pencemaran nama baik.  Di sini permasalahanya, Ia menuturkan dalam beberapa kasus, saksi ahli yang didatangkan tak punya kapasitas. “Bahkan terkadang, pelapor yang mendatangkan saksi ahli sehingga independensi saksi ini dipertanyakan,” kata Damar.</p>
        <p>Damar melihat pasal karet di dalam beleid ITE ini menjadi salah satu penyebab angka kebebasan berpendapat di Indonesia terus mengalami penurunan. Berdasarkan indeks kebebasan yang dirilis Freedom House pada 2019, Indonesia masuk kategori kuning yang artinya tak terlalu bebas.</p>
        <p>Lembaga pemantau kebebasan dan demokrasi yang bermarkas di New York Amerika ini juga menyebut, dari skala satu sebagai yang paling buruk sampai tujuh yang terbaik, kebebasan sipil berada di angka 4.</p>
        <img src="foto/3.jpg" alt="grafis tempo">
        <figcaption> Grafis Skor Kebebasan Sipil Indonesia - TEMPO</figcaption>
        <p>Melihat kondisi tersebut, Paguyuban Korban UU ITE menilai penghapusan pasal karet sangat penting. Arsyad ingin kriminalisasi menggunakan beleid itu harus dihentikan. Apalagi, kata dia, ada penyalahgunaan pelaporan UU ITE. “Pelapor biasanya punya motif balas dendam, barter kasus, membungkam kritik, shock therapy, dan persekusi kelompok,” kata Arsyad.</p>
        <p>Makanya, Paguyuban Korban UU ITE dan SAFENet mendesak agar dua pasal karet di dalam UU ITE ini dihapus. Toh, kata Damar, beleid pencemaran nama baik dan ujaran kebencian sudah ada di dalam KUHP.  “Sebagai gantinya setiap perkara ini bisa lewat jalur perdata,” kata Damar.</p>
<iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110093215001' allowfullscreen frameborder=0></iframe>
<figcaption> Arsyad, Pengacara Korban UU ITE: Divonis Bebas Karena Tak Terbukti Mencemarkan Nama Baik - TEMPO </figcaption>
    </article>
</div>
<div id="artikel-username01" class="artikel-hide">
    <article>
        <h1>Ramsyiah, Dosen Universitas Islam Negeri Alauddin: Tersangka Karena Mengkritik Dekan</h1>
        <p>Ramsyiah Tasruddin tak menyangka perkara dugaan pencemaran nama baik yang dua tahun lalu menghantuinya ujug-ujug mencuat pada awal September 2019. &ldquo;Saya kaget polisi langsung menyerahkan surat penetapan tersangka,&rdquo; kata Dosen Ilmu Komunikasi Fakultas Dakwah dan Komunikasi Universitas Islam Negeri Alauddin, Makassar kepada Tempo, pada Sabtu 19 Oktober 2019.</p>
        <p>Dalam surat berkop Kepolisian Resor Gowa itu polisi membidik Ramsyiah dengan Pasal 45 (3) juncto Pasal 27 (3) Undang-Undang Nomor 19 Tahun 2016 tentang Perubahan atas Undang-Undang Nomor 11 Tahun 2008 tentang Informasi dan Transaksi Elektronik dengan ancaman hukuman maksimal 4 tahun dan atau Pasal 310 KUHP tentang penghinaan.</p>
        <p>Ramsyiah menjadi tersangka setelah dilaporkan oleh Wakil Dekan III Fakultas Dakwah dan Komunikasi Nur Syamsiah pada medio 2017. Pangkal perkaranya, obrolan para dosen di grup percakapan WhatsApp terbatas bernama SAVE FDK UIN Alauddin.&rdquo; Ramsyiah termasuk satu dari 30 dosen yang menjadi anggota grup.&nbsp;</p>
        <p>Ramsyiah bercerita persoalan ini bermula ketika Mahasiswa Fakultas Dakwah dan Komunikasi meminjam laboratorium fakultas untuk tempat praktek siaran radio pada Mei 2017.&nbsp;</p>
        <p>Rupanya, kegiatan ini tak mendapat restu dari Wakil Dekan III Fakultas Dakwah dan Komunikasi Nur Syamsiah. Ia menilai kegiatan di Radio Kampus tersebut ternyata beraktivitas di luar aturan yang telah ditentukan.&nbsp;</p>
        <p>Kemudian, Syamsiah meminta mahasiswa mengunci laboratorium itu dan mengambil kuncinya. &ldquo;Padahal itu kan laboratorium tempatnya anak-anak praktek,&rdquo; kata Ramsyiah. Insiden ini kemudian menjadi pembicaraan di grup WhatsApp Save LDK UIN Alauddin.</p>
        <p>Ramsyiah mengatakan salah satu pembicaraan, misalnya, mempertanyakan sikap Nur Syamsiah yang melarang aktivitas radio itu. Padahal, mereka merasa seharusnya larangan menjadi tupoksi Wakil Dekan I.</p>
        <p>Karena kasus penutupan Radio Syiar, para dosen pun meminta Dekan Ilmu Komunikasi bersikap. Mereka memberikan meminta kepada Dekan agar Radio Syiar bisa dibuka kembali. &ldquo;Jadi tidak ada niat mencemarkan nama baik, ini curhat. Saya sudah minta maaf sama ibu Nur Syamsiah juga,&rdquo; katanya.</p>
        <p>Sementara itu, Nur Syamsiah mengatakan tak tahu menahu mengapa hanya Ramsyiah yang menjadi tersangka. &ldquo;Padahal saya melaporkan banyak dosen,&rdquo; kata Nur Syamsiah. &ldquo;Tapi yang bersangkutan sudah diproses hukum dan tersangka, berarti ada ujaran kebencian.&rdquo;</p>
        <p>Pengacara Ramsyiah yang juga Kepala Divisi Hak Sipil dan Politik LBH Makassar, Abdul Azis Dumpa, mengatakan penetapan tersangka kepada Ramsyiah adalah bentuk kriminalisasi lantaran sikap kritisnya di kampus. Menurut dia, materi yang dibahas di grup Whatsapp oleh 30 dosen tersebut bukanlah untuk kepentingan pribadi. &ldquo;Ini kan percakapan di internal, konsepnya untuk kepentingan umum,&rdquo; kata Azis.&nbsp;</p>
        <p>Menurut dia, obrolan grup WA internal kampus itu membahas tentang masalah internal penguncian radio syiar. Abdul Azis mengatakan selain itu, anggota grup juga berupaya untuk mencari penyelesaian dari insiden tersebut.&nbsp;</p>
        <p>Selain itu, Azis menyayangkan bahwa laporan ini datang dari dunia kampus yang seharusnya mengedepankan dialog dan sikap kritis. &ldquo;Kami meminta agar proses hukum terhadap dosen Ramsiah ini segera dihentikan dan meminta pihak UIN Alauddin untuk menyelesaikan persoalan ini secara kekeluargaan dan melalui mekanisme Internal,&rdquo; ujarnya.</p>
        <p>Azis melihat kasus ini juga menunjukkan bahwa penggunaan UU ITE selalu dilatarbelakangi konflik antara pelapor dan terlapor. Aturan itu digunakan sebagai alat untuk balas dendam.&nbsp;</p>
        <p>Dalam skala lebih besar, Azis mendesak agar pasal-pasal karena di dalam UU ITE ini dihapus, karena telah memakan banyak korban dan selalu menjadi alat kriminalisasi. &ldquo;Obrolan Ramsyiah di grup WA bukan bukan merupakan tindak pidana penghinaan atau pencemaran nama baik sebagaimana dimaksud dalam pasal 27 ayat 3 UU ITE dan 310 KUHP, kata Aziz.&nbsp;</p>
        <p>Kepala Sub Bagian (Kasubag) Hubungan Masyarakat Kepolisian Resor Gowa, Ajun Komisaris Polisi Mangatas Tambunan mengatakan polisi punya alasan kuat untuk menetapkan Ramsyiah sebagai tersangka. Penyidik, kata dia, telah menggelar perkara yang dikuatkan dengan keterangan saksi sebanyak 17 orang, tiga diantaranya adalah ahli bahasa, IT dan hukum pidana. &ldquo;Tersangka juga kita telah mintai keterangan dua kali sebagai saksi,&rdquo; ucapnya.</p>
<b> Didit Haridyadi (Makassar)</b>
          </article>
</div>
<div id="artikel-username02" class="artikel-hide">
    <article>
        <h1>Veronica Koman, Aktivis HAM: Menjadi Tersangka karena Cuitan Dia Soal Papua</h1>
        <p>AKTIVIS Hak Asasi Manusia (HAM) Veronica Koman tak kaget ketika Kepolisian Daerah Jawa Timur mengumumkan dia menjadi tersangka. &ldquo;Sudah lama saya menduga hal seperti ini bakal terjadi,&rdquo; kata Veronica ketika dihubungi pada Rabu, 27 November 2019.&nbsp;</p>
<p>Polisi menuding pengacara hak asasi manusia dan pendamping mahasiswa Papua di Surabaya itu memprovokasi dan menyebarkan berita bohong di media sosial.&nbsp;</p>
<p>"Dari hasil gelar perkara tadi malam akhirnya kami menetapkan yang bersangkutan sebagai tersangka," kata Kepala Polda Jawa Timur, Inspektur Jenderal Luki Hermawan, saat konferensi pers, Rabu, 4 September 2019.</p>
<p>Luki mengatakan Veronica menyebarkan provokasi di media sosial terkait insiden di asrama mahasiswa asal Papua di Surabaya pada 16 Agustus 2019. Polisi memastikan Veronica memang tak ada di asrama ketika pengepungan. Tetapi, Luki menuturkan ia aktif menyebarkan provokasi.</p>
<p>Polisi menjerat Veronica dengan pasal berlapis. Salah satunya, beleid soal menyebarkan kebencian dalam Undang-undang Informasi dan Transaksi Elektronik.</p>
<p>Luki kemudian merinci beberapa kalimat yang menurut polisi merupakan provokasi dan berita bohong. &ldquo;Dia mengatakan seruan mobilisasi aksi monyet turun ke jalan untuk besok di Jayapura," kata Luki. Selain itu, Luki mengatakan Veronica juga menulis ada 43 mahasiswa Papua di Surabaya ditangkap tanpa alasan jelas, 5 orang terluka dan 1 terkena tembakan gas air mata.</p>
<p>Polda Jawa Timur sudah mengirimkan surat ke pihak Divisi Hubungan Internasional (Divhubinter) Polri untuk menerbitkan red notice atas Veronica. Polisi pun menyurati Direktorat Jenderal Imigrasi untuk meminta passport Veronica dicabut.</p>
<iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110115920001' allowfullscreen frameborder=0></iframe>
<figcaption> Cerita Veronica - TEMPO </figcaption>
<p>Twitt yang dipersoalkan polisi ini bermula dari insiden pengepungan asrama Mahasiswa Papua pada 16 Agustus 2019. Kala itu, aparat dan sejumlah ormas mendatangi asrama mahasiswa Papua di Surabaya. Mereka datang ke sana karena mendapat kabar mahasiswa yang ada di dalam sana merusak tiang bendera merah putih.</p>
<p>Belakangan, pengepungan ini menjadi pemantik gerakan Mahasiswa Papua di beberapa daerah. Mereka menuntut pemerintah turun tangan mengusut insiden pengepungan yang juga diwarnai ujaran bernada rasis kepada para mahasiswa.</p>
<p>Veronica mengatakan kriminalisasi yang menimpanya hanyalah satu dari sekian banyak kasus intimidasi besar-besaran yang sedang dialami orang Papua saat ini. Ia berpendapat, pemerintah pusat beserta aparatur nampak tidak kompeten dalam menyelesaikan konflik berkepanjangan di Papua. "Hingga harus mencari kambing hitam atas apa yang terjadi saat ini," kata dia. "Cara seperti ini justru memperdalam luka dan memperuncing konflik Papua."&nbsp;</p>
<p>Veronica mengatakan sudah menyadari bakal terjerat dengan UU ITE, &ldquo;Kan yang paling karet dan paling gampang buat jerat saya ya UU ITE ini,&rdquo; kata dia.</p>
<p>Kepolisian, kata Veronica, telah menyalahgunakan wewenangnya. Ia juga menyebut upaya penetapan tersangka ini berlebihan. Menurut Veronica, ia sama sekali tak pernah menyebarkan provokasi apalagi berita bohong soal Papua.</p>
<p>Ia mengatakan seluruh twitt-nya berdasarkan fakta dan kejadian di lapangan. &ldquo;Semua yang berhubungan dengan Papua pasti tertutup, makanya saya mencoba memberikan informasi yang utuh soal kondisi di sana,&rdquo; kata Veronica.</p>
<p>Makanya, Veronica memutuskan tak akan pulang terlebih dahulu ke Indonesia. Ia menuturkan keberadaannya akan lebih berguna di Australia. Apalagi, kata dia, saat ini sudah mendekati tanggal 1 Desember yang oleh pemerintah dianggap selalu bakal ada gerakan besar-besaran kemerdekaan Papua.</p>
<p>Veronica curiga Pemerintah akan menutup akses internet pada 1 Desember. &ldquo;Makanya saya lebih baik tetap mengabarkan informasi seputar Papua dari sini,&rdquo; kata dia.</p>
    </article>
</div>
<div id="artikel-username03" class="artikel-hide">
    <article>
        <h1>Saiful Mahdi, Dosen Kampus Negeri: Menjadi Tersangka karena Mengkritik Seleksi CPNS Kampus</h1>
        <p>Dosen Fakultas Ilmu Matematika dan Ilmu Pengetahuan Alam (MIPA) Universitas Syiah Kuala Saiful Mahdi tak menyangka kritiknya terhadap proses rekrutmen Calon Pegawai Negeri Sipil di kampus tersebut berujung pada penetapan tersangka.</p>
        <p>Kepolisian Resor Kota Banda Aceh menetapkan Saiful sebagai tersangka pencemaran nama baik atau defarmasi pada akhir Agustus 2019. Polisi menjerat Saiful dengan Pasal 27 ayat (3) Undang-undang Nomor 19 Tahun 2016 tentang Informasi dan Transaksi Elektronik (UU ITE). &ldquo;Padahal, saya hanya mengkritik dan sama sekali tak menyinggung siapapun,&rdquo; kata Saiful kepada Tempo pada Kamis, 31 Oktober 2019.</p>
        <p>Saiful menuturkan pangkal persoalan ini bermula ketika Unsyiah menggelar rekrutmen CPNS pada akhir 2018. Belakangan, ia mendapat cerita dari beberapa orang bahwa ada pegawai di Unsyiah yang ikut seleksi untuk pos dosen Fakultas Teknik namun tak lolos. Padahal, kata dia, seluruh nilai si pegawai ini lebih dari cukup. Alih-alih, kampus malah meloloskan orang lain.</p>
        <p>Kemudian, Saiful mencurahkan uneg-unegnya soal penerimaan CPNS ini di grup bernama &ldquo;Unsyiah Kita&rdquo; pada Maret 2019. Ia menulis &ldquo;<em>Innalillahiwainnailaihirajiun. Dapat kabar duka matinya akal sehat dalam jajaran pimpinan FT Unsyiah saat tes PNS kemarin. Bukti determinisme teknik itu sangat mudah dikorup? Gong Xi Fat Cai!!! Kenapa ada fakultas yang pernah berjaya kemudian memble? Kenapa ada fakultas baru begitu membanggakan? Karena meritokrasi berlaku sejak rekrutmen hanya pada medioker atau yang terjerat &ldquo;hutang&rdquo; yang takut meritokrasi</em>.&rdquo;</p>
        <iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110107730001' allowfullscreen frameborder=0></iframe>
        <figcaption> Cerita Saiful - TEMPO </figcaption>
        <p>Status ini berbuntut panjang, Senay Unsyiah sempat meminta klarifikasi kepada Saiful pada 18 Maret 2019. Menurut Saiful, dalam pertemuan ini senat meminta penjelasan kepada dia soal status tersebut.</p>
        <p>Belakangan, rektor Unsyiah mengirim surat kepada Saiful Mahdi perihal Teguran Pelanggaran Etika Akademik pada 6 Mei 2019. Surat itu meminta Saiful segera meminta maaf kepada pimpinan Fakultas Teknik. Saiful keberatan dengan surat dari rektorat itu. Alasannya, ia sama sekali tidak pernah mendapat undangan untuk sidang etik. &ldquo;Pertemuan dengan senat hanya klarifikasi,&rdquo; kata dia.&nbsp;</p>
        <p>Kemudian, Saiful mendapat panggilan sebagai saksi kasus pencemaran nama baik di Polresta Banda Aceh pada medio Mei 2019. Dua kali diperiksa sebagai saksi, Polisi menetapkan Saiful sebagai tersangka pada Jumat, 30 Agustus 2019. Polisi pun sudah melimpahkan berkas perkara Saiful ke Kejaksaan Negeri Aceh pada Rabu, 27 November 2019.</p>
        <p>Sementara itu, Rektor Universitas Syiah Kuala Samsul Rizal mengatakan sidang etik kampus sebenarnya sudah memeriksa Saiful Mahdi. &ldquo;Senat Universitas menyatakan dia harus meminta maaf karena menyebarkan kabar tak benar tapi dia menolak meminta maaf,&rdquo; kata Samsul kepada wartawan.&nbsp;</p>
        <p>Karena Saiful tak kunjung meminta maaf, Samsul mengatakan Dekan Fakultas Teknis memutuskan membawa perkara ini ke ranah hukum. &ldquo;Dekan Fakultas Teknik merasa nama baik lembaga yang ia pimpin sudah dicemarkan, makanya ia melaporkan Saiful ke polisi,&rdquo; kata Samsul.</p>
    </article>
</div>
<div id="artikel-username05" class="artikel-hide">
    <article>
        <h1>Anindya Sabrina, Mahasiswi: Dibidik Pencemaran Nama Baik Karena Cerita Soal Pelecehan Seksual</h1>
        <p>SEPUCUK surat berkop Kepolisian Resor Kota Besar Surabaya itu seperti menghantam ulu hati Anindya Sabrina. Diantar oleh dua orang yang mengaku sebagai anggota polisi pada medio Agustus 2018, lelayang itu menjelaskan Polrestabes Surabaya sudah memulai penyidikan dugaan pencemaran nama baik dengan terlapor Anindya.</p>
        <p>&ldquo;Saya dapat surat perintah penyidikan, padahal saya tidak pernah pernah diperiksa sama sekali sebagai saksi dalam penyelidikan,&rdquo; kata Anindya menceritakan ulang kejadian itu ketika ditemui di Bogor pada Jumat, 18 Oktober 2019.&nbsp;</p>
        <p>Dalam surat itu, Anindya dilaporkan oleh Ketua Ikatan Keluarga Besar Papua Surabaya (IKBPS), Pieter Frans Rumaseb, pada 25 Juli 2018 atas dugaan pencemaran nama baik. Ia melaporkan Anindya dengan Pasal 27 Undang-undang Informasi Transaksi Elektronik (UU ITE).</p>
        <p>Pangkal laporan ini adalah status yang diunggah Anindya di dinding Facebook-nya pada medio Agustus 2019. Saat itu, Anindya menuliskan kronologis dugaan pelecehan seksual yang menimpa mahasiswi Fakultas Hukum Universitas Narotama, Surabaya saat Satuan Polisi Pamong Praja Kota Surabaya menggelar operasi kependudukan di Asrama Mahasiswa Papua.</p>
        <p>Saat itu, Anindya dan beberapa kawannya menggelar nonton film bareng dan diskusi di asrama mahasiswa Papua yang terletak di Jalan Kalasan Nomor 10, Surabaya, Jawa Timur pada 6 Juli 2018.&nbsp;</p>
        <p>Asrama ini merupakan tempat tinggal yang sempat menjadi sorotan karena dikepung oleh aparatur penegak hukum dan ormas di Surabaya pada 16 Agustus 2019. Pengepungan ini berujung pada unjuk rasa di sejumlah kota dan menyulut kerusuhan di Papua. Anindya merupakan mahasiswi yang memang aktif mengadvokasi isu-isu Papua.&nbsp;</p>
        <p>Anindya menuturkan, malam itu, sekitar pukul 20.30 WIB, ketika diskusi sudah hampir selesai, polisi, TNI, dan Satpol PP Kota Surabaya mendatangi asrama. Anindya menuturkan aparat gabungan ini memaksa masuk ke asrama dengan dalih sedang menggelar operasi kependudukan. <br /><br /></p>
        <iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110088414001' allowfullscreen frameborder=0></iframe>
        <figcaption> Cerita Anindya - TEMPO </figcaption>
        <p>Anindya dan beberapa aktivis LBH Surabaya kemudian menanyakan surat tugas. Tapi petugas menolak. Aparat, kata Anindya, sempat memaksa masuk sehingga berujung cekcok. Belakangan, Petugas menyeret Anindya dan kawan-kawannya menjauhi asrama. &ldquo;Ketika penyeretan itu ada bapak-bapak yang sengaja meremas payudara saya,&rdquo; kata Anindya. &ldquo;Saya sempat teriak tapi petugas diam saja.&rdquo;&nbsp;</p>
        <p>Beberapa hari kemudian, Anindya melaporkan insiden pelecehan seksual ini ke polisi. Namun, ia mengatakan tak pernah ada tanggapan dari kepolisian. Hingga ia akhirnya memutuskan mengunggah cerita tersebut di Facebook. Status ini yang kemudian digunakan Pieter untuk melaporkan Anindya.</p>
        <p>Anindya menuturkan ajaibnya ia sama sekali tak mengenal Pieter. Bahkan, kata dia, status Facebook yang menjadi pangkal permasalahan ini pun sama sekali tak menyinggung nama Pieter.&nbsp;</p>
        <p>Kepala Satuan Reserse Kriminal Polrestabes Surabaya, Ajun Komisaris Besar Sudamiran, mengatakan kasus dugaan pencemaran nama baik yang menjerat Anindya masih terus berlanjut. "Itu masih jalan. Cuma kami perlu pendalaman," kata dia singkat kepada saat Tempo, Senin, 11 November 2019.</p>
        <p>Adapun terkait kasus dugaan pelecehan yang dialami Anindya, Sudamiran mengaku polisi sudah menindaklanjutinya. Namun setelah dilakukan penyelidikan tak terbukti. "Buktinya nggak ada juga. Saksi-saksi juga kurang mendukung," katanya sembari membantah adanya diskriminatif dalam menangani kasus.</p>
        <p>Sementara Pieter mengatakan ia melaporkan Anindya karena dirasa mencemarkan nama baiknya. "Kalau tidak ada keterkaitan dengan saya, nggak mungkin saya melaporkan dia," ujar pria menjabat Kepala Bidang Ketertiban Umum dan Ketentraman Masyarakat Satpol PP Kota Surabaya itu.&nbsp;</p>
        <p>Dia menegaskan pelaporan itu dalam kapasitasnya sebagai Ketua Ikatan Keluarga Besar Papua Surabaya bukan mewakili institusi tempatnya bekerja.</p>
        <p>Anindya mengatakan perkara ini sudah menguras energi dan pikirannya. Bahkan, ia curiga polisi sengaja menggantung perkara ini. &ldquo;Saya sudah diperiksa tiga kali dan selalu dipanggil ketika akan ada diskusi soal Papua,&rdquo; kata dia. &ldquo;Saya lebih tenang kalau perkara ini segera naik ke persidangan agar fair.&rdquo; </p>
        <b><strong>Nur Hadi (Surabaya)</strong></b>
    </article>
</div>
<div id="artikel-username04" class="artikel-hide">
    <article>
        <h1>Furqan Ermansyah alias Rudi Lombok, Pengusaha Travel:  Menjadi Terpidana Karena Mengkritik Dinas Pariwisata</h1>
        <p>SENIN, 11 Mei 2015, semestinya menjadi hari membahagiakan bagi Furqan Ermansyah. Anak bungsunya yang duduk di kelas III sekolah dasar hari itu genap berusia 8 tahun. Keluarga pun telah menyiapkan perayaan kecil-kecilan: makan malam bersama di sebuah restoran cepat saji. Namun rencana itu buyar ketika sore harinya Furqan menelepon ke rumah. Ia menyampaikan kabar buruk.</p>
        <p>Siang itu Furqan menjalani pemeriksaan kedua di Kepolisian Daerah Nusa Tenggara Barat. Hingga larut malam, tak ada tanda-tanda pemeriksaan dengan polisi bakal segera rampung. "Ternyata penyidik menahan saya," kata Furqan, menceritakan ulang peristiwa itu pada Rabu, 27 November 2019.</p>
        <p>Keesokan harinya, istri Furqan, Murni Hayanti Fatimah, mendatangi kantor polisi bersama pengacara. Mereka mengajukan penangguhan penahanan Furqan. Namun polisi menolak permohonan itu. Furqan pun meminta istrinya tak menceritakan penahanan dia kepada ketiga anaknya.</p>
        <p>Furqan berurusan dengan polisi setelah dilaporkan Kepala Badan Promosi Pariwisata Nusa Tenggara Barat Taufan Rahmadi pada Desember tahun lalu. Taufan menuding Furqan mencemarkan namanya lewat tulisan di jejaring sosial Facebook. Polisi lantas menjerat Furqan dengan Pasal 27 ayat 3 dan Pasal 45 ayat 1 Undang-Undang Informasi dan Transaksi Elektronik (ITE).</p>
        <p>Furqan termasuk anggota aktif di forum diskusi yang sering membahas perkembangan pariwisata di Nusa Tenggara Barat itu. Di Facebook, ia memakai nama beken Rudy Lombok&mdash;julukan semasa kecilnya. Furqan sendiri sudah 26 tahun berkecimpung di bidang usaha perjalanan. Terakhir ia memiliki sebuah biro travel.</p>
<iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110114805001' allowfullscreen frameborder=0></iframe>
<figcaption> Cerita Rudi - TEMPO </figcaption>
        <p>Furqan mempertanyakan alasan situs milik lembaga pemerintah, www.bppdntb.com, mempromosikan paket wisata dari salah seorang agen pariwisata di Lombok. Menurut dia, situs milik lembaga pemerintah semestinya tidak mencari untung.&nbsp;</p>
        <p>Apalagi operasionalisasi situs itu sudah dibiayai anggaran daerah. Setelah muncul kritik itu, situs milik Badan Promosi Pariwisata tersebut sempat ditutup. Ketika www.bppdntb.com muncul lagi, tawaran paket jalan-jalan di situs tersebut sudah hilang.</p>
        <p>Dua tulisan berikutnya diunggah Furqan pada 21 Januari 2015 dan 5 Februari 2015. Kedua tulisan menyoroti perhelatan "Tambora Menyapa Dunia" yang sepi peminat. Furqan menilai perhelatan itu tak berhasil menyedot pengunjung karena panitia memang "tidak cakap". Di samping itu, ia menganggap iklan Badan Promosi Pariwisata tentang acara tersebut lebih menonjolkan profil Taufan Rahmadi ketimbang gambaran potensi wisata sesungguhnya.</p>
        <p>Rupanya, kritik Furqan membuat gerah pegawai Badan Promosi Pariwisata NTB. "Kami tak alergi jika dikritik, tapi ini sudah menjurus ke fitnah," ucap Taufan, ketika diwawancara Tempo pada 2015. Setelah menggelar rapat dengan semua pegawai, Taufan pun melaporkan Furqan ke polisi. Furqan pun menjadi tersangka.</p>
        <p>Furqan mengatakan selama menyandang status tersangka. Ia kehilangan mata pencaharian sebagai penyedia jasa wisata. &ldquo;Penahanan saya ditangguhkan tapi saya jadi tahanan kota sehingga tak bisa kemana-mana,&rdquo; kata dia.&nbsp;</p>
        <p>Perkara Furqan melaju ke meja hijau. Pada Pengadilan Negeri Mataram memvonis Furqan bersalah. Majelis hakim menyatakan ia terbukti secara sah dan meyakinkan bersalah melakukan tindak pidana pencemaran nama baik. Hakim memvonis Furqan 10 bulan penjara dengan masa percobaan selama 1 tahun.</p>
        <p>Kini masa hukuman Furqan sudah selesai. Ia pun memutuskan bergabung dengan Paguyuban Korban UU ITE (Paku ITE). &ldquo;Di sana saya melihat aturan ITE ini memang lentur,&rdquo; kata Furqan. Ia melihat banyak orang menjadi korban karena ketimpangan relasi sosial. Makanya, Furqan pun mendesak agar beleid pencemaran nama baik dalam UU ITE dihilangkan.&nbsp;</p>
            </article>
</div>
<div id="artikel-username06" class="artikel-hide">
    <article>
        <h1>Zakki Amali, Wartawan: Dilaporkan Rektor Unnes karena Tulisannya di Media Massa</h1>
        <p>Tawaran menjadi dosen di Universitas Negeri Semarang itu datang kepada Zakki Amali beberapa bulan setelah pihak kampus melaporkan wartawan ini ke Polda Jawa Tengah. Rektorat Unnes melaporkan Zakki menggunakan Pasal 27 ayat 3 Undang-Undang Informasi dan Transaksi Elektronik ((UU ITE) tentang pencemaran nama baik dengan ancaman empat tahun penjara atas liputan Zakki di Serat.id.&nbsp;</p>
        <p>&ldquo;Dia menawari aku mengajar di Unnes sebagai bentuk permintaan maaf,&rdquo; kata Zakki pada Kamis, 7 November 2019. Namun, Zakki menolak tawaran tersebut. Ia meminta Kampus Unnes yang terletak di Gunung Pati mengajukan permintaan maaf secara terbuka dan diliput media.&nbsp;</p>
        <p>Persoalan ini berawal ketika Zakki menurunkan laporan di Serat.id tentang dugaan plagiarisme yang dilakukan Rektor Unnes Fathur Rahman pada Juni 2018.&nbsp;</p>
        <p>Kala itu, Zakki menemukan naskah karya Fathur berjudul &ldquo;Kode Bahasa dalam Literasi Sosial Santri: Kajian Sosiolinguistik di Pesantren Banyumas&rdquo; mirip dengan naskah &ldquo;Pemakaian Kode Bahasa dalam Interaksi Sosial Santri dan Implikasinya bagi Rekayasa Bahasa Indonesia: Kajian Sosiolinguistik di Pesantren Banyumas&rdquo; karya Anif Rida.</p>
        <p>Karya Fathur terbit di Jurnal Penelitian Bahasa, Sastra, dan Pengajarannya (Litera) Universitas Negeri Yogyakarta Volume 3 Nomor 1 Tahun 2004. Sedangkan tulisan Anif Rida muncul di Prosiding Konferensi Linguistik Tahunan Atma Jaya (Kolita) 1 Universitas Katolik Atma Jaya Jakarta 2003.</p>
        <p>Rektorat Unnes kemudian melaporkan Zakki ke Direktorat Kriminal Khusus Polda Jawa Tengah pada 21 Juli 2018. Polisi sudah memanggil Zakki dua kali pada 16 Oktober dan 14 November 2018. Namun, ia memilih tak datang. </p>
        <p>Zakki tak memenuhi panggilan karena menganggap polisi mengabaikan Undang-Undang Pers. &ldquo;Sebagai bentuk protes kepada kepolisian karena dia menjalankan pemeriksaan tanpa menghormati UU Pers,&rdquo; katanya.</p>
        <p>Menurut Zakki, surat panggilan kedua itu merupakan yang terakhir. Setelah itu ia tak lagi menerima panggilan dari kepolisian. &ldquo;Belum pernah menjalani pemeriksaan karena ketika dipanggil tidak hadir,&rdquo; kata Zakki.</p>
        <p>Zakki kemudian mengadukan kasus yang menjeratnya ke Dewan Pers. Ia meminta perlindungan hukum dan penilaian karya kepada Dewan Pers. Permintaan tersebut ia sampaikan secara formal melalui surat dan informal. &ldquo;Setiap ketemu Dewan Pers saya lobi,&rdquo; ucapnya.</p>
        <p>Menurut Zakki, masalah ini cukup menguras waktu, tenaga, dan pikirannya. Pasalnya, ketika awal mendapat panggilan dari kepolisian upaya advokasi berlangsung siang dan malam. &ldquo;Sampai sekarang masih berlanjut tetapi tidak intens,&rdquo; katanya. &ldquo;Di Sekretariat Aliansi Jurnalis Independen Kota Semarang orang datang dan pergi menanyakan kasus.&rdquo;</p>
        <p>Kedua orang tuanya juga turut menanggung pikiran karena kasus tersebut. Zakki telah berusaha merahasiakan informasi bahwa ia dilaporkan polisi kepada orangtuanya. Namun, berita tersebut sampai di telinga orangtuanya. &ldquo;Bapak ibu berpesan yang penting saya benar,&rdquo;ujarnya.</p>
        <p>Kini, Zakki tetap menekuni profesinya sebagai jurnalis dengan bergabung di Tirto.id di Yogyakarta. &ldquo;Tidak punya pikiran ke Yogyakarta tetapi karena ada tawaran dan diterima, saya pikir kenapa tidak diambil,&rdquo; tuturnya.</p>
        <p>Terpisah, Rektor Unnes Fathur menyebut perselisihan antara dirinya dengan Zakki merupakan kasus lama. Menurut Fathur, kasus tersebut telah selesai. &ldquo;Kasus lama sudah selesai,&rdquo; katanya melalui pesan Whatsapp, Jumat, 8 November 2019.</p>
        <p>Fathur mengklaim bahwa kedua pihak telah saling memaafkan. Namun, ketika Tempo mengajukan permintaan wawancara, Fathur tak bersedia. Permintaan wawancara kembali Tempo layangkan melalui pesan Whatsapp pada Senin, 11 November 2019, tetapi Fathur tak menanggapi.</p>
        <b>Jamal Abdul Nashr (Semarang)</b>
      </article>
</div>
<div id="artikel-username07" class="artikel-hide">
    <article>
        <h1>Ecky Lamoh, Musikus: Menjadi Tersangka karena Curhat di Facebook</h1>
        <p>SUARA Alexander Theodore Lamoh alias <a href="https://www.tempo.co/tag/ecky-lamoh">Ecky Lamoh</a> meninggi ketika menceritakan ulang bagaimana ia terjerat pasal pencemaran nama baik dalam Undang-undang Nomor 19 Tahun 2016 tentang Informasi dan Transaksi Elektronik (UU ITE).&nbsp;</p>
        <p>&ldquo;Dua tahun saya dibayang-bayangi kasus ini, menjadi tersangka kemudian sidang, sampai putus kontrak, saya kehilangan banyak hal,&rdquo; kata eks vokalis grup band Edane ini pada Senin, 25 Oktober 2019.&nbsp;</p>
        <p>Pengadilan Negeri Yogyakarta pada akhirnya memang membebaskan Ekcy dari jerat pasal karet UU ITE pada Rabu, 5 Februari 2019. Namun, kasus ini, kata dia, telah merenggut banyak hal termasuk keluarga.</p>
        <p>Ecky dilaporkan ke Polda Yogya oleh kakak iparnya sendiri pada Oktober 2017 atas dugaan pencemaran nama baik dengan dasar Pasal 27 ayat 3 UU ITE. Pelaporan itu buntut atas keluhan Ecky yang diunggah di akun Facebooknya medio September 2015 dan Maret 2016.&nbsp;</p>
        <iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110092164001' allowfullscreen frameborder=0></iframe>
<figcaption> Cerita Ecky - TEMPO </figcaption>
        <p>Saat itu Ecky mengeluhkan laporannya soal dugaan penggelapan sertifikat tanah yang tak kunjung ditindaklanjuti polres Bantul sejak 2013 sampai 2015. Setelah membuat status itu, Ecky pun dilaporkan ke polisi pada Oktober 2017 dan langsung menjadi tersangka di bulan yang sama. Ecky mulai disidang di Pengadilan Negeri Bantul pada Juni 2018.</p>
        <p>Direktur Lembaga Bantuan Hukum Yogyakarta yang menjadi pengacara Ecky, Yogi Zul Fadhli, mengatakan hakim mempertimbangkan membebaskan Ecky atas dasar pasal 310 KUHP. Karena bagaimanapun untuk penerapan pasal 27 ayat 3 UU ITE tetap harus dimaknai dan melihat induknya yakni pasal 310 KUHP.</p>
        <p>Adapun kutipan pasal 310 yang dijadikan dasar hakim memutus bebas Ecky yakni bahwa tindakan penghinaan terjadi manakala seseorang menuduhkan sesuatu hal. Suatu hal itu berupa perbuatan kepada orang lain. Dari pemahaman itu, kalimat kuncinya adalah perbuatan.</p>
        <p>Dan hakim, ujar Yogi, menilai status facebook yang dibuat Ecky tidak bisa dimaknai menuduhkan sesuatu dalam hal perbuatan. Sebab yang diposting Ecky hanya menerangkan soal status hukum terlapor dan ia menyebut &lsquo;tersangka&rsquo;. &ldquo;Status Ecky itu tidak memenuhi unsur tafsir penghinaan sesuai yang diatur pasal 310 KUHP, maka unsur lain secara otomatis teranulir,&rdquo; ujarnya.</p>
        <p>Dalam persidangan itu, ujar Yogi, hakim memang mempertimbangkan bahwa dalam pasal 27 ayat 3<a href="https://pilpres.tempo.co/read/1171574/sandiaga-uno-bentuk-tim-khusus-untuk-kaji-uu-ite"> UU ITE </a>mengatur soal ketentuan mendistribusikan status yang dituduh mencemarkan nama baik. &ldquo;Unsur mendistribusikannya memang terpenuhi, karena secara faktual Ecky mengunggah itu, tapi kontennya sendiri terbukti tak mengandung penghinaan,&rdquo; ujarnya.</p>
          </article>
</div>
<div id="artikel-username08" class="artikel-hide">
    <article>
        <h1>Username 8</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?</p>
    </article>
</div>
<div id="artikel-username09" class="artikel-hide">
    <article>
        <h1>Saidah Saleh, Ibu Rumah Tangga: Divonis Bersalah karena Dituduh Mencemarkan Nama Baik</h1>
        <p>GARA-gara nomor telepon yang lama tak pernah dipakai, Saidah Saleh Syamlan menjadi tersangka gara-gara dituduh mencemarkan nama baik. &ldquo;Saya dituduh mencemarkan nama baik perusahaan tempat suami bekerja,&rdquo; kata ibu rumah tangga asal Surabaya ini menceritakan ulang kisahnya pada Kamis, 28 November 2019.</p>
  <p>Cerita ini bermula ketika kuasa hukum perusahaan tempat suami Saidah bekerja melaporkan pemilik nomor 08135780*** ke polisi pada 12 September 2017. Sebab, nomor ini mengirimkan pesan ke sebuah bank. Pengacara beranggapan pesan tersebut bernada mencemarkan nama baik sehingga mengakibatkan perusahaan kesulitan mendapatkan pinjaman dari bank.</p>
  <p>Belakangan, polisi menyebut nomor tersebut atas nama Saidah Saleh Syamlan. Setelah serangkaian pemeriksaan, polisi menetapkan Saidah sebagai tersangka. Perkara ini pun meluncur mulus ke persidangan.</p>
  <p>Masalahnya, Saidah mengatakan nomor tersebut sudah tak pernah ia pakai. Ia menuturkan memang sempat menggunakan nomor tersebut. Namun, karena telepon selulernya rusak ia pun menelantarkan nomor itu. &ldquo;Saya juga tidak pernah mengirim WhatsApp seperti yang dituduhkan,&rdquo; kata Saidah.</p>
  <p>Saidah mengatakan, toh kalaupun memang dia yang mengirim pesan tersebut, maka percakapannya bersifat pribadi bukan masuk kategori pencemaran nama baik di ruang publik.&nbsp;</p>
<iframe width="100%" height="500px" src='https://players.brightcove.net/3734026318001/BkT6OdRkX_default/index.html?videoId=6110104266001' allowfullscreen frameborder=0></iframe>
<figcaption> Cerita Saidah - TEMPO </figcaption>
  <p>SafeNet sebagai organisasi yang mendampingi Saidah melihat ada beberapa argumen yang dipaksakan. Pertama, tidak ada alat bukti yang sah. Barang bukti berupa hasil tangkap layar bukanlah alat bukti yang sah dalam persidangan UU ITE.&nbsp;</p>
  <p>SafeNet melihat pemeriksaan lewat forensik digital atas perangkat yang digunakan untuk mengirim pesan Whatsapp haruslah dilakukan. Hal tersebut untuk membuktikan bahwa pesan itu dikirim oleh Saidah atau bukan.</p>
  <p>Belakangan, kasus Saidah melenggang sampai meja hijau. Jaksa penuntut umum menuntut Saidah 1 tahun 5 bulan penjara penjara dan denda sebesar Rp 500 juta subsider 3 bulan kurungan sesuai pasal 27 ayat (3) jo Pasal 45 ayat (3) Undang-undang Informasi dan Transaksi Elektronik. Kemudian Pengadilan Negeri Surabaya memutus Saidah bersalah dengan pidana penjara 10 bulan dan denda Rp 5 juta subsider 1 bulan kurungan pada Februari 2019.&nbsp;</p>
  <p>Saidah pun memutuskan mengajukan banding. Pada Agustus 2019, Pengadilan Tinggi Surabaya memutus bebas Saidah karena tidak ada bukti yang menguatkan bahwa ia mengirimkan pesan tersebut. &ldquo;Saya belajar banyak dari kasus ini, dan saya yakin UU ITE memang hanya menguntungkan yang berkuasa, tumpul ke atas, tajam ke bawah,&rdquo; kata dia.</p>
    </article>
</div>
